/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx,js,jsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
          950: '#052e16',
        },
        earth: {
          50: '#fefcf3',
          100: '#fef6e0',
          200: '#fceabd',
          300: '#f5d08e',
          400: '#d4a373',
          500: '#c28b56',
          600: '#a47148',
          700: '#8b5e3c',
        },
        cream: {
          50: '#fffef7',
          100: '#fefbeb',
          200: '#fdf6d1',
          300: '#fbeeb0',
          400: '#f7e28a',
          500: '#f2d264',
          600: '#ddb846',
          700: '#b89530',
        },
        warm: {
          50: '#fefaf4',
          100: '#faf5eb',
          200: '#f5edd8',
          300: '#ede0c0',
          400: '#dccfaa',
          500: '#c9b88e',
        },
        forest: {
          50: '#f0f7f0',
          100: '#d4ead4',
          200: '#a8d5a8',
          300: '#6dba6d',
          400: '#3d9e3d',
          500: '#2d7a2d',
          600: '#1f5c1f',
        },
      },
      fontSize: {
        xs: ['0.6rem', { lineHeight: '0.8rem' }],
        sm: ['0.7rem', { lineHeight: '1rem' }],
        base: ['0.8rem', { lineHeight: '1.2rem' }],
        lg: ['0.9rem', { lineHeight: '1.4rem' }],
        xl: ['1rem', { lineHeight: '1.4rem' }],
        '2xl': ['1.2rem', { lineHeight: '1.6rem' }],
        '3xl': ['1.5rem', { lineHeight: '1.8rem' }],
        '4xl': ['1.8rem', { lineHeight: '2rem' }],
        '5xl': ['2.4rem', { lineHeight: '1' }],
        '6xl': ['3rem', { lineHeight: '1' }],
        '7xl': ['3.6rem', { lineHeight: '1' }],
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'Georgia', 'serif'],
        accent: ['var(--font-accent)', 'cursive'],
      },
      animation: {
        float: 'float 4s ease-in-out infinite',
        'float-delayed': 'float 4s ease-in-out 1s infinite',
        'fade-in': 'fade-in 0.5s ease-out forwards',
        'fade-in-up': 'fade-in-up 0.5s ease-out forwards',
        'slide-in-left': 'slide-in-left 0.4s ease-out forwards',
        'slide-in-right': 'slide-in-right 0.4s ease-out forwards',
        shimmer: 'shimmer 2s infinite linear',
        marquee: 'marquee 60s linear infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-subtle': 'bounce-subtle 2s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-up': {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-left': {
          from: { opacity: '0', transform: 'translateX(-20px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-right': {
          from: { opacity: '0', transform: 'translateX(20px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        marquee: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-50%)' },
        },
        'bounce-subtle': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
      },
      boxShadow: {
        glow: '0 0 20px rgba(22, 163, 74, 0.15)',
        'glow-lg': '0 0 40px rgba(22, 163, 74, 0.2)',
        'inner-glow': 'inset 0 0 20px rgba(22, 163, 74, 0.1)',
      },
      backgroundImage: {
        'brand-gradient': 'linear-gradient(135deg, #15803d, #22c55e)',
        'earth-gradient': 'linear-gradient(135deg, #d4a373, #a47148)',
        'hero-gradient': 'linear-gradient(135deg, #f0fdf4, #dcfce7, #fefcf3)',
        glass: 'linear-gradient(135deg, rgba(255,255,255,0.1), rgba(255,255,255,0))',
      },
    },
  },
  plugins: [],
};
